function T_i = Create_Transformation(in1)
%CREATE_TRANSFORMATION
%    T_I = CREATE_TRANSFORMATION(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    08-Mar-2019 19:15:19

dh1 = in1(:,1);
dh2 = in1(:,2);
dh3 = in1(:,3);
dh4 = in1(:,4);
t2 = sin(dh4);
t3 = cos(dh4);
t4 = cos(dh1);
t5 = sin(dh1);
T_i = reshape([t3,t2,0.0,0.0,-t2.*t4,t3.*t4,t5,0.0,t2.*t5,-t3.*t5,t4,0.0,dh2.*t3,dh2.*t2,dh3,1.0],[4,4]);
