function c = get_C(in1)
%GET_C
%    C = GET_C(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    08-Mar-2019 19:15:22

q1 = in1(1,:);
q2 = in1(2,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = cos(q1);
t6 = t3+t5;
t7 = t4.*t6;
t8 = sin(q1);
t9 = t4+t8;
t10 = t3.*t9;
t11 = -t7+t10;
c = reshape([0.0,t11,0.0,t11,t11,0.0,t7-t3.*t9,0.0,0.0,0.0,0.0,0.0],[3,2,2]);
