function phi_q = get_Phi(in1)
%GET_PHI
%    PHI_Q = GET_PHI(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    08-Mar-2019 19:15:22

q1 = in1(1,:);
q2 = in1(2,:);
phi_q = cos(q1+q2).*(1.47e2./5.0)+cos(q1).*(4.9e1./1.0e1);
