function J_n_w = get_J_ang(in1)
%GET_J_ANG
%    J_N_W = GET_J_ANG(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    08-Mar-2019 19:15:20

J_n_w = reshape([0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0],[3,2,2]);
